/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/DJet.glb
*/

// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Layout3D(props) {
  const { nodes, materials } = useGLTF('./models/Layout3D.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PumpHpElica.geometry} material={materials.MetalGloss} position={[17.687, 22.018, 12.176]} rotation={[0, -0.003, 0.022]} scale={2.345} />
      <mesh geometry={nodes.PumpHpRotore.geometry} material={materials.MetalGloss} position={[17.686, 22.001, 18.195]} rotation={[Math.PI / 2, 0, 0.003]} scale={[0.27, 0.944, 0.27]} />
      <mesh geometry={nodes.PumpHpTarga.geometry} material={materials.MetalGloss} position={[11.855, 20, 13.992]} rotation={[0, -0.003, 0]} scale={2.345} />
      <mesh geometry={nodes.PumpHPBody.geometry} material={materials.HpPump} position={[11.855, 20, 13.992]} rotation={[0, -0.003, 0]} scale={2.345} />
      <mesh geometry={nodes.HpPumpFilter.geometry} material={materials.Pipe} position={[26.98, 20.15, 12.019]} rotation={[0, 0.006, 0]} scale={[0.445, 0.616, 0.445]} />
      <mesh geometry={nodes.HpPumpCarter.geometry} material={materials.MetalMate} position={[13.888, 19.985, 14.001]} rotation={[0, -0.003, 0]} scale={1.908} />
      <mesh geometry={nodes.PumpHpElicaCL.geometry} material={materials.MetalGloss} position={[-36.732, 22.018, 12.176]} rotation={[0, -0.003, 0.022]} scale={2.345} />
      <mesh geometry={nodes.PumpHpRotoreCL.geometry} material={materials.MetalGloss} position={[-36.733, 22.001, 18.195]} rotation={[Math.PI / 2, 0, 0.003]} scale={[0.27, 0.944, 0.27]} />
      <mesh geometry={nodes.PumpHpTargaCL.geometry} material={materials.MetalGloss} position={[-42.564, 20, 13.992]} rotation={[0, -0.003, 0]} scale={2.345} />
      <mesh geometry={nodes.PumpHPBodyCL.geometry} material={materials['HpPump.001']} position={[-42.564, 20, 13.992]} rotation={[0, -0.003, 0]} scale={2.345} />
      <mesh geometry={nodes.HpPumpFilterCL.geometry} material={materials.Pipe} position={[-27.439, 20.15, 12.019]} rotation={[0, 0.006, 0]} scale={[0.445, 0.616, 0.445]} />
      <mesh geometry={nodes.HpPumpCarterCL.geometry} material={materials.MetalMate} position={[-40.531, 19.985, 14.001]} rotation={[0, -0.003, 0]} scale={1.908} />
      <mesh geometry={nodes.GroupPumpingBody.geometry} material={materials.MetalMate} position={[21.751, 21.623, 12.314]} rotation={[0, -0.003, 0]} scale={1.908} />
      <mesh geometry={nodes.GroupPumpingRotore.geometry} material={materials.MetalGloss} position={[21.765, 21.613, 17.429]} rotation={[Math.PI / 2, 0, 0.003]} scale={[0.22, 0.768, 0.22]} />
      <mesh geometry={nodes.GroupPumpingBodyCL.geometry} material={materials.MetalMate} position={[-32.668, 21.623, 12.314]} rotation={[0, -0.003, 0]} scale={1.908} />
      <mesh geometry={nodes.GroupPumpingRotoreCL.geometry} material={materials.MetalGloss} position={[-32.654, 21.613, 17.429]} rotation={[Math.PI / 2, 0, 0.003]} scale={[0.22, 0.768, 0.22]} />
      <mesh geometry={nodes.GroupPumpingCircleBolt.geometry} material={materials.MetalGloss} position={[25.649, 21.481, 15.894]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt001.geometry} material={materials.MetalGloss} position={[25.648, 21.481, 15.521]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt002.geometry} material={materials.MetalGloss} position={[25.647, 21.481, 15.259]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt003.geometry} material={materials.MetalGloss} position={[25.646, 21.481, 14.882]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt004.geometry} material={materials.MetalGloss} position={[25.646, 21.481, 14.615]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt005.geometry} material={materials.MetalGloss} position={[25.645, 21.481, 14.232]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt.geometry} material={materials.MetalGloss} position={[25.557, 22.626, 14.302]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt001.geometry} material={materials.MetalGloss} position={[25.558, 22.626, 14.78]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt002.geometry} material={materials.MetalGloss} position={[25.56, 22.626, 15.893]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt003.geometry} material={materials.MetalGloss} position={[25.559, 22.626, 15.364]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt004.geometry} material={materials.MetalGloss} position={[25.219, 22.626, 14.302]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt005.geometry} material={materials.MetalGloss} position={[25.221, 22.626, 14.781]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt006.geometry} material={materials.MetalGloss} position={[25.223, 22.626, 15.893]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt007.geometry} material={materials.MetalGloss} position={[25.222, 22.626, 15.365]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingHead.geometry} material={materials.MetalMate} position={[25.747, 21.481, 14.429]} rotation={[Math.PI / 2, 0, -1.573]} scale={[0.308, 0.021, 0.308]} />
      <mesh geometry={nodes.GroupPumpingCircleBolt006.geometry} material={materials.MetalGloss} position={[-28.771, 21.481, 15.894]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt007.geometry} material={materials.MetalGloss} position={[-28.771, 21.481, 15.521]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt008.geometry} material={materials.MetalGloss} position={[-28.772, 21.481, 15.259]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt009.geometry} material={materials.MetalGloss} position={[-28.773, 21.481, 14.882]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt010.geometry} material={materials.MetalGloss} position={[-28.774, 21.481, 14.615]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingCircleBolt011.geometry} material={materials.MetalGloss} position={[-28.774, 21.481, 14.232]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt008.geometry} material={materials.MetalGloss} position={[-28.863, 22.626, 14.302]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt009.geometry} material={materials.MetalGloss} position={[-28.862, 22.626, 14.78]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt010.geometry} material={materials.MetalGloss} position={[-28.859, 22.626, 15.893]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt011.geometry} material={materials.MetalGloss} position={[-28.86, 22.626, 15.364]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt012.geometry} material={materials.MetalGloss} position={[-29.2, 22.626, 14.302]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt013.geometry} material={materials.MetalGloss} position={[-29.199, 22.626, 14.781]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt014.geometry} material={materials.MetalGloss} position={[-29.196, 22.626, 15.893]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingUpBolt015.geometry} material={materials.MetalGloss} position={[-29.198, 22.626, 15.365]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={0.023} />
      <mesh geometry={nodes.GroupPumpingHead001.geometry} material={materials.MetalMate} position={[-28.673, 21.481, 14.429]} rotation={[Math.PI / 2, 0, -1.573]} scale={[0.308, 0.021, 0.308]} />
      <mesh geometry={nodes.HpPumpPipe.geometry} material={materials.Pipe} position={[25.409, 21.105, 16.831]} rotation={[0, -0.003, 0]} />
      <mesh geometry={nodes.HpPumpPipe001.geometry} material={materials.Pipe} position={[25.264, 21.332, 14.284]} rotation={[0, 0.006, 0]} />
      <mesh geometry={nodes.HpPumpPipe002.geometry} material={materials.Pipe} position={[27.455, 21.326, 12.01]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh geometry={nodes.HpPumpPipe003.geometry} material={materials.Pipe} position={[21.826, 21.108, 21.197]} rotation={[0.112, 1.568, 3.03]} scale={[0.75, 1, 1]} />
      <mesh geometry={nodes.HpPumpPipe004.geometry} material={materials.Pipe} position={[27.437, 21.334, 12.014]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.HpPumpPipe005.geometry} material={materials.Pipe} position={[-29.011, 21.105, 16.831]} rotation={[0, -0.003, 0]} />
      <mesh geometry={nodes.HpPumpPipe006.geometry} material={materials.Pipe} position={[-29.155, 21.332, 14.284]} rotation={[0, 0.006, 0]} />
      <mesh geometry={nodes.HpPumpPipe007.geometry} material={materials.Pipe} position={[-26.964, 21.326, 12.01]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh geometry={nodes.HpPumpPipe008.geometry} material={materials.Pipe} position={[-32.594, 21.108, 21.197]} rotation={[0.112, 1.568, 3.03]} scale={[0.75, 1, 1]} />
      <mesh geometry={nodes.HpPumpPipe009.geometry} material={materials.Pipe} position={[-26.983, 21.334, 12.014]} rotation={[0, -1.57, 0]} />
      <group position={[8.734, 24.556, 19.481]} rotation={[Math.PI / 2, 0, 1.563]} scale={[0.372, 1.104, 0.372]}>
        <mesh geometry={nodes.Cylinder074.geometry} material={materials.Pipe} />
        <mesh geometry={nodes.Cylinder074_1.geometry} material={materials.MetalGloss} />
      </group>
      <group position={[7.215, 24.556, 19.481]} rotation={[Math.PI / 2, 0, 1.563]} scale={[0.372, 1.104, 0.372]}>
        <mesh geometry={nodes.Cylinder070.geometry} material={materials.Pipe} />
        <mesh geometry={nodes.Cylinder070_1.geometry} material={materials.MetalMate} />
      </group>
      <mesh geometry={nodes.InletComponentsPortata.geometry} material={materials['Componentes.Inlet.Barometer']} position={[8.104, 26.863, 19.494]} rotation={[0, 1.571, 0]} scale={[0.112, 0.017, 0.112]} />
      <mesh geometry={nodes.EmulsifierBody.geometry} material={materials.Emulsifier} position={[10.899, 20.195, 23.83]} rotation={[0, 1.569, 0]} scale={1.077} />
      <mesh geometry={nodes.EmulsifierBolt001.geometry} material={materials.MetalGloss} position={[12.509, 21.141, 21.869]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt002.geometry} material={materials.MetalGloss} position={[12.51, 21.701, 21.559]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt003.geometry} material={materials.MetalGloss} position={[12.51, 20.551, 21.619]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt004.geometry} material={materials.MetalGloss} position={[12.512, 20.551, 20.726]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt005.geometry} material={materials.MetalGloss} position={[12.513, 21.141, 20.443]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt006.geometry} material={materials.MetalGloss} position={[12.512, 21.701, 20.726]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierElica.geometry} material={materials.MetalGloss} position={[10.063, 21.123, 21.151]} rotation={[0, 1.569, 0.022]} scale={1.077} />
      <mesh geometry={nodes.EmulsifierPipe001.geometry} material={materials.Pipe} position={[13.923, 21.122, 21.973]} rotation={[-0.027, -0.002, -1.571]} scale={[0.361, 1.073, 0.361]} />
      <mesh geometry={nodes.EmulsifierPipe002.geometry} material={materials.Pipe} position={[14.541, 21.103, 20.748]} rotation={[0, 1.569, 0]} scale={0.677} />
      <mesh geometry={nodes.EmulsifierPipe003.geometry} material={materials.Pipe} position={[14.005, 25.363, 19.399]} rotation={[0, 1.569, 0]} scale={0.677} />
      <mesh geometry={nodes.EmulsifierPipe004.geometry} material={materials.Pipe} position={[13.001, 24.553, 19.398]} rotation={[Math.PI / 2, 0, -1.569]} scale={[0.361, 1.073, 0.361]} />
      <mesh geometry={nodes.EmulsifierTarga.geometry} material={materials.MetalGloss} position={[10.899, 20.195, 23.83]} rotation={[0, 1.569, 0]} scale={1.077} />
      <mesh geometry={nodes.FilterBarometerInlet.geometry} material={materials['Emulsifier.Barometer.Outlet']} position={[9.88, 26.822, 19.393]} rotation={[0, 1.569, 0]} scale={[0.109, 0.016, 0.109]} />
      <mesh geometry={nodes.FilterBarometerOutlet.geometry} material={materials['Emulsifier.Barometer.Inlet']} position={[13.615, 26.822, 19.399]} rotation={[0, 1.569, 0]} scale={[0.109, 0.016, 0.109]} />
      <mesh geometry={nodes.FilterBody.geometry} material={materials.MetalMate} position={[13.616, 23.336, 19.399]} rotation={[0, 1.569, 0]} scale={0.7} />
      <mesh geometry={nodes.FilterBolt001.geometry} material={materials.MetalGloss} position={[12.782, 25.373, 18.962]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt002.geometry} material={materials.MetalGloss} position={[12.781, 25.753, 19.397]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt003.geometry} material={materials.MetalGloss} position={[12.78, 25.373, 19.826]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt004.geometry} material={materials.MetalGloss} position={[12.781, 24.924, 19.397]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt008.geometry} material={materials.MetalGloss} position={[11.366, 25.373, 19.824]} rotation={[-Math.PI / 2, 0, 1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBottom.geometry} material={materials.MetalMate} position={[11.469, 20.659, 19.395]} rotation={[Math.PI / 2, 0, -1.569]} scale={[0.361, 1.073, 0.361]} />
      <mesh geometry={nodes.FilterHead.geometry} material={materials.MetalMate} position={[9.258, 24.553, 19.392]} rotation={[Math.PI / 2, 0, -1.569]} scale={[0.361, 1.073, 0.361]} />
      <group position={[11.371, 25.753, 19.395]} rotation={[-Math.PI / 2, 0, 1.569]} scale={0.046}>
        <mesh geometry={nodes.Bolt033.geometry} material={materials.MetalGloss} />
        <mesh geometry={nodes.Bolt033_1.geometry} material={materials.Pipe} />
      </group>
      <mesh geometry={nodes.FilterValve.geometry} material={materials['Filter.Valve']} position={[8.262, 26.516, 19.39]} rotation={[0, 1.569, 0]} scale={[0.189, 0.028, 0.189]} />
      <group position={[-45.686, 24.556, 19.481]} rotation={[Math.PI / 2, 0, 1.563]} scale={[0.372, 1.104, 0.372]}>
        <mesh geometry={nodes.Cylinder058.geometry} material={materials.Pipe} />
        <mesh geometry={nodes.Cylinder058_1.geometry} material={materials.MetalGloss} />
      </group>
      <group position={[-47.204, 24.556, 19.481]} rotation={[Math.PI / 2, 0, 1.563]} scale={[0.372, 1.104, 0.372]}>
        <mesh geometry={nodes.Cylinder059.geometry} material={materials.Pipe} />
        <mesh geometry={nodes.Cylinder059_1.geometry} material={materials.MetalMate} />
      </group>
      <mesh geometry={nodes.InletComponentsPortataCL.geometry} material={materials['Componentes.Inlet.Barometer.001']} position={[-46.315, 26.863, 19.494]} rotation={[0, 1.571, 0]} scale={[0.112, 0.017, 0.112]} />
      <mesh geometry={nodes.EmulsifierBodyCL.geometry} material={materials['Emulsifier.001']} position={[-43.52, 20.195, 23.83]} rotation={[0, 1.569, 0]} scale={1.077} />
      <mesh geometry={nodes.EmulsifierBolt007.geometry} material={materials.MetalGloss} position={[-41.91, 21.141, 21.869]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt008.geometry} material={materials.MetalGloss} position={[-41.909, 21.701, 21.559]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt009.geometry} material={materials.MetalGloss} position={[-41.909, 20.551, 21.619]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt010.geometry} material={materials.MetalGloss} position={[-41.907, 20.551, 20.726]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt011.geometry} material={materials.MetalGloss} position={[-41.907, 21.141, 20.443]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierBolt012.geometry} material={materials.MetalGloss} position={[-41.907, 21.701, 20.726]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.018} />
      <mesh geometry={nodes.EmulsifierElicaCL.geometry} material={materials.MetalGloss} position={[-44.356, 21.123, 21.151]} rotation={[0, 1.569, 0.022]} scale={1.077} />
      <mesh geometry={nodes.EmulsifierPipe005.geometry} material={materials.Pipe} position={[-40.496, 21.122, 21.973]} rotation={[-0.027, -0.002, -1.571]} scale={[0.361, 1.073, 0.361]} />
      <mesh geometry={nodes.EmulsifierPipe006.geometry} material={materials.Pipe} position={[-39.879, 21.103, 20.748]} rotation={[0, 1.569, 0]} scale={0.677} />
      <mesh geometry={nodes.EmulsifierPipe007.geometry} material={materials.Pipe} position={[-40.415, 25.363, 19.399]} rotation={[0, 1.569, 0]} scale={0.677} />
      <mesh geometry={nodes.EmulsifierPipe008.geometry} material={materials.Pipe} position={[-41.419, 24.553, 19.398]} rotation={[Math.PI / 2, 0, -1.569]} scale={[0.361, 1.073, 0.361]} />
      <mesh geometry={nodes.EmulsifierTarga001.geometry} material={materials.MetalGloss} position={[-43.52, 20.195, 23.83]} rotation={[0, 1.569, 0]} scale={1.077} />
      <mesh geometry={nodes.FilterBarometerInletCL.geometry} material={materials['Emulsifier.Barometer.Outlet.001']} position={[-44.54, 26.822, 19.393]} rotation={[0, 1.569, 0]} scale={[0.109, 0.016, 0.109]} />
      <mesh geometry={nodes.FilterBarometerOutletCL.geometry} material={materials['Emulsifier.Barometer.Inlet.001']} position={[-40.804, 26.822, 19.399]} rotation={[0, 1.569, 0]} scale={[0.109, 0.016, 0.109]} />
      <mesh geometry={nodes.FilterBodyCL.geometry} material={materials.MetalMate} position={[-40.804, 23.336, 19.399]} rotation={[0, 1.569, 0]} scale={0.7} />
      <mesh geometry={nodes.FilterBolt005.geometry} material={materials.MetalGloss} position={[-41.637, 25.373, 18.962]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt006.geometry} material={materials.MetalGloss} position={[-41.638, 25.753, 19.397]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt007.geometry} material={materials.MetalGloss} position={[-41.639, 25.373, 19.826]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt009.geometry} material={materials.MetalGloss} position={[-41.638, 24.924, 19.397]} rotation={[Math.PI / 2, 0, -1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBolt010.geometry} material={materials.MetalGloss} position={[-43.053, 25.373, 19.824]} rotation={[-Math.PI / 2, 0, 1.569]} scale={0.046} />
      <mesh geometry={nodes.FilterBottom001.geometry} material={materials.MetalMate} position={[-42.95, 20.659, 19.395]} rotation={[Math.PI / 2, 0, -1.569]} scale={[0.361, 1.073, 0.361]} />
      <mesh geometry={nodes.FilterHead001.geometry} material={materials.MetalMate} position={[-45.161, 24.553, 19.392]} rotation={[Math.PI / 2, 0, -1.569]} scale={[0.361, 1.073, 0.361]} />
      <group position={[-43.049, 25.753, 19.395]} rotation={[-Math.PI / 2, 0, 1.569]} scale={0.046}>
        <mesh geometry={nodes.Bolt073.geometry} material={materials.MetalGloss} />
        <mesh geometry={nodes.Bolt073_1.geometry} material={materials.Pipe} />
      </group>
      <mesh geometry={nodes.FilterValveCL.geometry} material={materials['Filter.Valve.001']} position={[-46.157, 26.516, 19.39]} rotation={[0, 1.569, 0]} scale={[0.189, 0.028, 0.189]} />
      <mesh geometry={nodes.ResinaturaBody.geometry} material={materials['Transparent.Pesante']} position={[17.332, 5.608, 1.214]} rotation={[-Math.PI, 0.007, -Math.PI]} scale={6.197} />
      <mesh geometry={nodes.ResinaturaCinghia001.geometry} material={materials['Transparent.Pesante']} position={[10.436, 0.978, 0.418]} rotation={[-1.335, -0.001, -1.57]} scale={2.902} />
      <mesh geometry={nodes.ResinaturaCinghia002.geometry} material={materials['Transparent.Pesante']} position={[9.742, 0.978, 0.418]} rotation={[-1.335, -0.001, -1.57]} scale={2.902} />
      <mesh geometry={nodes.ResinaturaCircolo001.geometry} material={materials['Transparent.Pesante']} position={[10.013, 0.847, 0.706]} rotation={[Math.PI / 2, 0, -1.57]} scale={[3.699, 0.9, 3.699]} />
      <mesh geometry={nodes.ResinaturaCircolo002.geometry} material={materials['Transparent.Pesante']} position={[10.077, -0.599, 12.476]} rotation={[Math.PI / 2, 0, -1.57]} scale={[2.318, 0.731, 2.318]} />
      <mesh geometry={nodes.ResinaturaCircolo003.geometry} material={materials.Transparent} position={[10.652, -0.599, 12.476]} rotation={[Math.PI / 2, 0, -1.57]} scale={[0.484, 1.762, 0.484]} />
      <mesh geometry={nodes.ResinaturaMotorBody.geometry} material={materials['Transparent.Pesante']} position={[18.565, -4.143, 2.15]} rotation={[0, -1.569, 0]} scale={4.169} />
      <mesh geometry={nodes.ResinaturaMotorElica.geometry} material={materials['Transparent.Pesante']} position={[21.84, -0.555, 12.507]} rotation={[0, -1.569, 0.022]} scale={4.169} />
      <mesh geometry={nodes.ResinaturaRotore001.geometry} material={materials.Transparent} position={[10.806, 0.847, 0.707]} rotation={[Math.PI / 2, 0, -1.57]} scale={[0.772, 2.169, 0.772]} />
      <mesh geometry={nodes.ResinaturaBody001.geometry} material={materials['Transparent.Pesante']} position={[-36.924, 5.608, 1.214]} rotation={[-Math.PI, 0.007, -Math.PI]} scale={6.197} />
      <mesh geometry={nodes.ResinaturaCinghia003.geometry} material={materials['Transparent.Pesante']} position={[-43.821, 0.978, 0.418]} rotation={[-1.335, -0.001, -1.57]} scale={2.902} />
      <mesh geometry={nodes.ResinaturaCinghia004.geometry} material={materials['Transparent.Pesante']} position={[-44.514, 0.978, 0.418]} rotation={[-1.335, -0.001, -1.57]} scale={2.902} />
      <mesh geometry={nodes.ResinaturaCircolo004.geometry} material={materials['Transparent.Pesante']} position={[-44.243, 0.847, 0.706]} rotation={[Math.PI / 2, 0, -1.57]} scale={[3.699, 0.9, 3.699]} />
      <mesh geometry={nodes.ResinaturaCircolo005.geometry} material={materials['Transparent.Pesante']} position={[-44.18, -0.599, 12.476]} rotation={[Math.PI / 2, 0, -1.57]} scale={[2.318, 0.731, 2.318]} />
      <mesh geometry={nodes.ResinaturaCircolo006.geometry} material={materials.Transparent} position={[-43.535, -0.599, 12.476]} rotation={[Math.PI / 2, 0, -1.57]} scale={[0.484, 1.762, 0.484]} />
      <mesh geometry={nodes.ResinaturaMotorBody001.geometry} material={materials['Transparent.Pesante']} position={[-35.692, -4.143, 2.15]} rotation={[0, -1.569, 0]} scale={4.169} />
      <mesh geometry={nodes.ResinaturaMotorElica001.geometry} material={materials['Transparent.Pesante']} position={[-32.417, -0.555, 12.507]} rotation={[0, -1.569, 0.022]} scale={4.169} />
      <mesh geometry={nodes.ResinaturaRotore002.geometry} material={materials.Transparent} position={[-43.45, 0.847, 0.707]} rotation={[Math.PI / 2, 0, -1.57]} scale={[0.772, 2.169, 0.772]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Transparent.Light']} position={[6.384, 19.979, 1.517]} scale={[52.598, 17.806, 28.301]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Transparent} position={[-10.111, -4.586, 12.258]} rotation={[0, 0, -Math.PI]} scale={[-74.004, -17.806, -39.042]} />
      <mesh geometry={nodes.PipeT.geometry} material={materials.Pipe} position={[3.02, 25.41, 20.002]} rotation={[-1.572, 0, -3.13]} scale={[0.249, 0.46, 0.249]} />
      <mesh geometry={nodes.ValvePosition.geometry} material={materials.ValveDistyributionInjectors} position={[3.015, 25.151, 16.76]} rotation={[-1.572, 0, 0.004]} scale={[0.201, 0.363, 0.201]} />
      <mesh geometry={nodes.ValveBody.geometry} material={materials.MetalMate} position={[3.025, 25.416, 17.415]} rotation={[3.14, -0.004, 0]} scale={[1.259, 0.612, 0.612]} />
      <mesh geometry={nodes.ValveBolts.geometry} material={materials.MetalGloss} position={[4.171, 25.8, 17.78]} rotation={[3.14, -0.004, -Math.PI / 2]} scale={0.052} />
      <mesh geometry={nodes.ValveRotore.geometry} material={materials.Pipe} position={[3.021, 25.358, 18.751]} rotation={[1.566, 0, -0.004]} scale={[0.249, 0.843, 0.249]} />
      <mesh geometry={nodes.PipeTCL.geometry} material={materials.Pipe} position={[-51.399, 25.41, 20.002]} rotation={[-1.572, 0, -3.13]} scale={[0.249, 0.46, 0.249]} />
      <mesh geometry={nodes.ValvePositionCL.geometry} material={materials['ValveDistyributionInjectors.001']} position={[-51.404, 25.151, 16.76]} rotation={[-1.572, 0, 0.004]} scale={[0.201, 0.363, 0.201]} />
      <mesh geometry={nodes.ValveBodyCL.geometry} material={materials.MetalMate} position={[-51.394, 25.416, 17.415]} rotation={[3.14, -0.004, 0]} scale={[1.259, 0.612, 0.612]} />
      <mesh geometry={nodes.ValveBoltsCL.geometry} material={materials.MetalGloss} position={[-50.248, 25.8, 17.78]} rotation={[3.14, -0.004, -Math.PI / 2]} scale={0.052} />
      <mesh geometry={nodes.ValveRotoreCL.geometry} material={materials.Pipe} position={[-51.399, 25.358, 18.751]} rotation={[1.566, 0, -0.004]} scale={[0.249, 0.843, 0.249]} />
      <mesh geometry={nodes.IniettoreBody001.geometry} material={materials['Iniettore.001']} position={[50.422, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts001.geometry} material={materials.MetalGloss} position={[49.938, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents001.geometry} material={materials.Pipe} position={[50.115, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo001.geometry} material={materials.Pipe} position={[50.121, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody001CL.geometry} material={materials['Iniettore.011']} position={[-3.835, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts001CL.geometry} material={materials.MetalGloss} position={[-4.318, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents001CL.geometry} material={materials.Pipe} position={[-4.141, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo001CL.geometry} material={materials.Pipe} position={[-4.136, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody002.geometry} material={materials['Iniettore.002']} position={[49.075, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts002.geometry} material={materials.MetalGloss} position={[48.592, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents002.geometry} material={materials.Pipe} position={[48.769, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo002.geometry} material={materials.Pipe} position={[48.774, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody002CL.geometry} material={materials['Iniettore.012']} position={[-5.181, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts002CL.geometry} material={materials.MetalGloss} position={[-5.665, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents002CL.geometry} material={materials.Pipe} position={[-5.488, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo002CL.geometry} material={materials.Pipe} position={[-5.482, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody003.geometry} material={materials['Iniettore.003']} position={[47.728, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts003.geometry} material={materials.MetalGloss} position={[47.245, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents003.geometry} material={materials.Pipe} position={[47.422, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo003.geometry} material={materials.Pipe} position={[47.427, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody003CL.geometry} material={materials['Iniettore.013']} position={[-6.528, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts003CL.geometry} material={materials.MetalGloss} position={[-7.011, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents003CL.geometry} material={materials.Pipe} position={[-6.834, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo003CL.geometry} material={materials.Pipe} position={[-6.829, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody004.geometry} material={materials['Iniettore.004']} position={[44.262, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts004.geometry} material={materials.MetalGloss} position={[43.779, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents004.geometry} material={materials.Pipe} position={[43.956, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo004.geometry} material={materials.Pipe} position={[43.961, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody004CL.geometry} material={materials['Iniettore.014']} position={[-9.994, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts004CL.geometry} material={materials.MetalGloss} position={[-10.477, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents004CL.geometry} material={materials.Pipe} position={[-10.3, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo004CL.geometry} material={materials.Pipe} position={[-10.295, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody005.geometry} material={materials['Iniettore.005']} position={[42.944, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts005.geometry} material={materials.MetalGloss} position={[42.461, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents005.geometry} material={materials.Pipe} position={[42.638, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo005.geometry} material={materials.Pipe} position={[42.643, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody005CL.geometry} material={materials['Iniettore.015']} position={[-11.312, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts005CL.geometry} material={materials.MetalGloss} position={[-11.796, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents005CL.geometry} material={materials.Pipe} position={[-11.619, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo005CL.geometry} material={materials.Pipe} position={[-11.613, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody006.geometry} material={materials['Iniettore.006']} position={[41.583, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts006.geometry} material={materials.MetalGloss} position={[41.1, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents006.geometry} material={materials.Pipe} position={[41.277, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo006.geometry} material={materials.Pipe} position={[41.282, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody006CL.geometry} material={materials['Iniettore.016']} position={[-12.673, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts006CL.geometry} material={materials.MetalGloss} position={[-13.157, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents006CL.geometry} material={materials.Pipe} position={[-12.98, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo006CL.geometry} material={materials.Pipe} position={[-12.974, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody007.geometry} material={materials['Iniettore.007']} position={[40.222, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts007.geometry} material={materials.MetalGloss} position={[39.739, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents007.geometry} material={materials.Pipe} position={[39.916, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo007.geometry} material={materials.Pipe} position={[39.921, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody007CL.geometry} material={materials['Iniettore.017']} position={[-14.034, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts007CL.geometry} material={materials.MetalGloss} position={[-14.517, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents007CL.geometry} material={materials.Pipe} position={[-14.34, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo007CL.geometry} material={materials.Pipe} position={[-14.335, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody008.geometry} material={materials['Iniettore.008']} position={[38.883, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts008.geometry} material={materials.MetalGloss} position={[38.399, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents008.geometry} material={materials.Pipe} position={[38.576, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo008.geometry} material={materials.Pipe} position={[38.582, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody008CL.geometry} material={materials['Iniettore.018']} position={[-15.374, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts008CL.geometry} material={materials.MetalGloss} position={[-15.857, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents008CL.geometry} material={materials.Pipe} position={[-15.68, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo008CL.geometry} material={materials.Pipe} position={[-15.675, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody009.geometry} material={materials['Iniettore.009']} position={[37.543, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts009.geometry} material={materials.MetalGloss} position={[37.06, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents009.geometry} material={materials.Pipe} position={[37.237, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo009.geometry} material={materials.Pipe} position={[37.242, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody009CL.geometry} material={materials['Iniettore.019']} position={[-16.713, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts009CL.geometry} material={materials.MetalGloss} position={[-17.197, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents009CL.geometry} material={materials.Pipe} position={[-17.02, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo009CL.geometry} material={materials.Pipe} position={[-17.014, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody010.geometry} material={materials['Iniettore.010']} position={[36.182, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts010.geometry} material={materials.MetalGloss} position={[35.699, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents010.geometry} material={materials.Pipe} position={[35.876, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo010.geometry} material={materials.Pipe} position={[35.881, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.IniettoreBody010CL.geometry} material={materials['Iniettore.020']} position={[-18.074, 5.022, -0.978]} rotation={[-Math.PI, 1.567, -Math.PI]} />
      <mesh geometry={nodes.IniettoreBolts010CL.geometry} material={materials.MetalGloss} position={[-18.558, 6.296, -1.297]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={0.009} />
      <mesh geometry={nodes.IniettoreInletComponents010CL.geometry} material={materials.Pipe} position={[-18.38, 5.022, -0.702]} />
      <mesh geometry={nodes.IniettoreStelo010CL.geometry} material={materials.Pipe} position={[-18.375, 5.852, -0.981]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[0.471, 0.255, 0.471]} />
      <mesh geometry={nodes.PortataBolts.geometry} material={materials.MetalGloss} position={[30.08, 15.626, 12.051]} rotation={[-3.134, 0, 0]} scale={0.034} />
      <mesh geometry={nodes.Misuratore.geometry} material={materials.MisuratorePortata} position={[29.14, 16.365, 12.025]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.288} />
      <mesh geometry={nodes.PortataBody.geometry} material={materials.Pipe} position={[30.38, 14.071, 12.024]} rotation={[1.699, 1.564, -1.699]} scale={[0.266, 0.79, 0.266]} />
      <mesh geometry={nodes.PipeConnectionPortata.geometry} material={materials.Pipe} position={[28.672, 21.33, 12.007]} />
      <mesh geometry={nodes.PipeTransportToInjectors.geometry} material={materials.Pipe} position={[29.801, 14.922, 12.014]} />
      <mesh geometry={nodes.PipeFromMesamol.geometry} material={materials.Pipe} position={[-14.183, -3.526, 32.47]} />
      <mesh geometry={nodes.PipeFromGlue.geometry} material={materials.Pipe} position={[-1.535, 25.39, 19.535]} />
      <mesh geometry={nodes.Colonna001.geometry} material={materials.Transparent} position={[-44.713, 7.205, -25.729]} scale={[1, 11.857, 1]} />
      <mesh geometry={nodes.Colonna002.geometry} material={materials.Transparent} position={[-44.713, 7.205, 28.89]} scale={[1, 11.857, 1]} />
      <mesh geometry={nodes.Colonna003.geometry} material={materials.Transparent} position={[57.85, 7.205, 28.89]} scale={[1, 11.857, 1]} />
      <mesh geometry={nodes.Colonna004.geometry} material={materials.Transparent} position={[57.85, 7.205, -25.485]} scale={[1, 11.857, 1]} />
      <mesh geometry={nodes.PipeFromMesamolCL.geometry} material={materials.Pipe} position={[-68.606, -3.526, 32.47]} />
      <mesh geometry={nodes.PipeFromGlueCL.geometry} material={materials.Pipe} position={[-55.957, 25.39, 19.535]} />
      <mesh geometry={nodes.PortataBoltsCL.geometry} material={materials.MetalGloss} position={[-24.157, 15.626, 12.051]} rotation={[-3.134, 0, 0]} scale={0.034} />
      <mesh geometry={nodes.MisuratoreCL.geometry} material={materials['MisuratorePortata.001']} position={[-25.098, 16.365, 12.025]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.288} />
      <mesh geometry={nodes.PortataBodyCL.geometry} material={materials.Pipe} position={[-23.858, 14.071, 12.024]} rotation={[1.699, 1.564, -1.699]} scale={[0.266, 0.79, 0.266]} />
      <mesh geometry={nodes.PipeConnectionPortataCL.geometry} material={materials.Pipe} position={[-25.566, 21.33, 12.007]} />
      <mesh geometry={nodes.PipeTransportToInjectorsCL.geometry} material={materials.Pipe} position={[-24.436, 14.922, 12.014]} />
      <mesh geometry={nodes.PompaMesamolTarga.geometry} material={materials.MetalGloss} position={[-23.243, 1.39, 37.666]} rotation={[1.57, -0.002, -1.572]} scale={1.592} />
      <mesh geometry={nodes.PompaMesamolBody.geometry} material={materials.PompaMesamol} position={[-21.877, 2.811, 33.721]} rotation={[1.57, -0.002, -1.572]} scale={1.592} />
      <mesh geometry={nodes.PompaMesamolElica.geometry} material={materials.MetalGloss} position={[-21.874, 2.629, 33.708]} rotation={[1.57, -0.002, -1.55]} scale={1.592} />
      <mesh geometry={nodes.PompaMesamolPressostato.geometry} material={materials['PompaMesamol.Pressostato']} position={[-14.722, -1.342, 32.466]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.162, 0.024, 0.162]} />
      <mesh geometry={nodes.PompaMesamolPipePressostato.geometry} material={materials.Pipe} position={[-14.722, -2.823, 32.466]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.3, 0.045, 0.3]} />
      <mesh geometry={nodes.PompaMesamolPipeOutlet.geometry} material={materials.Pipe} position={[-19.222, -4.668, 32.439]} rotation={[1.571, -0.01, -1.572]} scale={[0.534, 1.585, 0.534]} />
      <mesh geometry={nodes.PompaMesamolRotore.geometry} material={nodes.PompaMesamolRotore.material} position={[-18.797, -3.242, 33.81]} rotation={[Math.PI / 2, 0, -1.572]} scale={[0.352, 0.967, 0.352]} />
      <mesh geometry={nodes.PompaMesamolOutlet.geometry} material={materials.MetalMate} position={[-18.75, -3.487, 31.94]} rotation={[-3.142, 1.57, 1.571]} scale={[0.216, 0.011, 0.216]} />
      <mesh geometry={nodes.PompaMesamolBolts.geometry} material={materials.MetalGloss} position={[-16.093, -2.926, 32.435]} rotation={[-1.571, 0.01, 1.572]} scale={0.068} />
      <mesh geometry={nodes.SiloMesamol.geometry} material={materials.MetalMate} position={[-41.409, 4.674, 43.962]} scale={[7.011, 9.227, 7.011]} />
      <mesh geometry={nodes.Mesamol.geometry} material={materials.Mesamol} position={[-41.574, 5.058, 43.857]} scale={[5.698, 7.26, 5.698]} />
      <mesh geometry={nodes.PompaMesamolTargaCL.geometry} material={materials.MetalGloss} position={[-77.532, 1.39, 37.666]} rotation={[1.57, -0.002, -1.572]} scale={1.592} />
      <mesh geometry={nodes.PompaMesamolBodyCL.geometry} material={materials['PompaMesamol.001']} position={[-76.166, 2.811, 33.721]} rotation={[1.57, -0.002, -1.572]} scale={1.592} />
      <mesh geometry={nodes.PompaMesamolElicaCL.geometry} material={materials.MetalGloss} position={[-76.163, 2.629, 33.708]} rotation={[1.57, -0.002, -1.55]} scale={1.592} />
      <mesh geometry={nodes.PompaMesamolPressostatoCL.geometry} material={materials['PompaMesamol.Pressostato.001']} position={[-69.011, -1.342, 32.466]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.162, 0.024, 0.162]} />
      <mesh geometry={nodes.PompaMesamolPipePressostatoCL.geometry} material={materials.Pipe} position={[-69.011, -2.823, 32.466]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.3, 0.045, 0.3]} />
      <mesh geometry={nodes.PompaMesamolPipeOutletCL.geometry} material={materials.Pipe} position={[-73.511, -4.668, 32.439]} rotation={[1.571, -0.01, -1.572]} scale={[0.534, 1.585, 0.534]} />
      <mesh geometry={nodes.PompaMesamolRotoreCL.geometry} material={nodes.PompaMesamolRotoreCL.material} position={[-73.086, -3.242, 33.81]} rotation={[Math.PI / 2, 0, -1.572]} scale={[0.352, 0.967, 0.352]} />
      <mesh geometry={nodes.PompaMesamolOutletCL.geometry} material={materials.MetalMate} position={[-73.039, -3.487, 31.94]} rotation={[-3.142, 1.57, 1.571]} scale={[0.216, 0.011, 0.216]} />
      <mesh geometry={nodes.PompaMesamolBoltsCL.geometry} material={materials.MetalGloss} position={[-70.382, -2.926, 32.435]} rotation={[-1.571, 0.01, 1.572]} scale={0.068} />
      <mesh geometry={nodes.PipeConnectionFromMesamolCL.geometry} material={materials.Pipe} position={[-72.421, -3.556, 36.572]} rotation={[0, 0, Math.PI]} />
      <mesh geometry={nodes.PipeConnectionFromMesamol.geometry} material={materials.Pipe} position={[-18.195, -3.556, 36.572]} />
    </group>
  )
}

export default Layout3D
